### ISSUE TITLE
Couldn't place player in world net.minecraft.ReportedException: Loading entity NBT

### ISSUE THREAD

**Issue by 3944Realms** [Viola-Siemens/Teleport-Master#3]
The Minecraft Version is 1.18.2
The Server is running  in a long time  without this mod,and I want add this mod but it seem that this mod didn't handler the nbt data correctly 
Here is the strack that the Server thrown:
[10:43:30] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
net.minecraft.ReportedException: Loading entity NBT
        at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1596) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin,pl:acces
stransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.am.json:EntityMix,pl:mixin:A}
        at net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:56) ~[server-1.18.2-20220404.173914-srg.jar%2
370!/:?] {re:classloading}
        at net.minecraft.server.players.PlayerList.m_11224_(PlayerList.java:301) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin
,re:classloading,pl:mixin:APP:mixins.am.json:PlayerListMix,pl:mixin:APP:servercore.common.mixins.json:features.dynamic.PlayerListMixin,pl:mi
xin:APP:servercore.common.mixins.json:optimizations.players.PlayerListMixin,pl:mixin:A}
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:136) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin
,re:classloading,pl:mixin:APP:mixins.am.json:PlayerListMix,pl:mixin:APP:servercore.common.mixins.json:features.dynamic.PlayerListMixin,pl:mi
xin:APP:servercore.common.mixins.json:optimizations.players.PlayerListMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[server-1.18.2-2022
0404.173914-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[server-1.18.2-20220
404.173914-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[server-1.18.2-202204
04.173914-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:classloadin
g,re:mixin}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-
srg.jar%2370!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixi
n,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?
] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixi
n,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mi
xin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mi
xin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) [?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.Tag.m_6458_()" because "p_129234_" is null
        at net.minecraft.nbt.NbtUtils.m_129233_(NbtUtils.java:189) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin,re:classloadi
ng}
        at net.minecraft.nbt.CompoundTag.m_128342_(CompoundTag.java:183) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin,re:comp
uting_frames,re:classloading}
        at net.minecraft.server.level.ServerPlayer.handler$zzj000$readTeleportMasterData(ServerPlayer.java:1684) ~[server-1.18.2-20220404.17
3914-srg.jar%2370!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl
:mixin:APP:tpmaster.mixins.json:ServerPlayerMixin,pl:mixin:APP:mixins.am.json:ServerPlayerMix,pl:mixin:APP:servercore.common.mixins.json:opt
imizations.players.ServerPlayerMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayer.m_7378_(ServerPlayer.java:311) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixi
n,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tpmaster.mixins.json
:ServerPlayerMixin,pl:mixin:APP:mixins.am.json:ServerPlayerMix,pl:mixin:APP:servercore.common.mixins.json:optimizations.players.ServerPlayer
Mixin,pl:mixin:A}
        at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1581) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin,pl:acces
stransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.am.json:EntityMix,pl:mixin:A}
        ... 14 more
[10:43:30] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@c038812[id=758cce80-d40a-37fe-b8fa
-7e062b21468d,name=R3944Realms,properties={},legacy=false] (/117.93.15.224:14474) lost connection: Invalid player data
[10:43:30] [Server thread/WARN] [minecraft/Connection]: handleDisconnection() called twice
[10:46:47] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
net.minecraft.ReportedException: Loading entity NBT
        at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1596) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin,pl:acces
stransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.am.json:EntityMix,pl:mixin:A}
        at net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:56) ~[server-1.18.2-20220404.173914-srg.jar%2
370!/:?] {re:classloading}
        at net.minecraft.server.players.PlayerList.m_11224_(PlayerList.java:301) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin
,re:classloading,pl:mixin:APP:mixins.am.json:PlayerListMix,pl:mixin:APP:servercore.common.mixins.json:features.dynamic.PlayerListMixin,pl:mi
xin:APP:servercore.common.mixins.json:optimizations.players.PlayerListMixin,pl:mixin:A}
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:136) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin
,re:classloading,pl:mixin:APP:mixins.am.json:PlayerListMix,pl:mixin:APP:servercore.common.mixins.json:features.dynamic.PlayerListMixin,pl:mi
xin:APP:servercore.common.mixins.json:optimizations.players.PlayerListMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[server-1.18.2-2022
0404.173914-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[server-1.18.2-20220
404.173914-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[server-1.18.2-202204
04.173914-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:classloadin
g,re:mixin}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-
srg.jar%2370!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixi
n,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?
] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixi
n,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mi
xin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mi
xin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) [?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.Tag.m_6458_()" because "p_129234_" is null
        at net.minecraft.nbt.NbtUtils.m_129233_(NbtUtils.java:189) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin,re:classloadi
ng}
        at net.minecraft.nbt.CompoundTag.m_128342_(CompoundTag.java:183) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin,re:comp
uting_frames,re:classloading}
        at net.minecraft.server.level.ServerPlayer.handler$zzj000$readTeleportMasterData(ServerPlayer.java:1684) ~[server-1.18.2-20220404.17
3914-srg.jar%2370!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl
:mixin:APP:tpmaster.mixins.json:ServerPlayerMixin,pl:mixin:APP:mixins.am.json:ServerPlayerMix,pl:mixin:APP:servercore.common.mixins.json:opt
imizations.players.ServerPlayerMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayer.m_7378_(ServerPlayer.java:311) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixi
n,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tpmaster.mixins.json
:ServerPlayerMixin,pl:mixin:APP:mixins.am.json:ServerPlayerMix,pl:mixin:APP:servercore.common.mixins.json:optimizations.players.ServerPlayer
Mixin,pl:mixin:A}
        at net.minecraft.world.entity.Entity.m_20258_(Entity.java:1581) ~[server-1.18.2-20220404.173914-srg.jar%2370!/:?] {re:mixin,pl:acces
stransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.am.json:EntityMix,pl:mixin:A}
        ... 14 more
[10:46:47] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@38857b83[id=****,name=*****,properties={},legacy=false] (/*****) lost connection: Invalid player data
[10:46:47] [Server thread/WARN] [minecraft/Connection]: handleDisconnection() called twice

**Comment by 3944Realms** [comment]
Upadted mod version to 1.0.2.
